### ISSUE TITLE
Experimental Results on BlocksWorld (4-steps, Vicuna-13B-V1.3)

### ISSUE THREAD

**Issue by artpli** [agentification/RAFA_code#2]
Hello authors, appreciate to your great work!

When I attempted to replicate the experimental results on Blocksworld (4-step setting, Vicuna-13B-V1.3), I found some discrepancies with the results stated in the paper. Could you please help me to check where the issue is?

Here are my results:
![image](https://github.com/agentification/RAFA_code/assets/47554045/e7f3b6ac-2161-4c44-b32d-0d70360c650e)

For RAP, the command I used was:
```
python -m torch.distributed.run --master_port 1034 --nproc_per_node 1 run_mcts.py --task mcts \
    --model_name Vicuna \
    --verbose False \
    --data data/blocksworld/step_4.json \
    --max_depth 4 \
    --name rap_roll60_13b_all \
    --rollouts 60 \
    --model_path lmsys/vicuna-13b-v1.3 \
    --num_gpus 1
```
For RAFA, the command was:
```
python -m torch.distributed.run --master_port 36977 --nproc_per_node 1 run_rafa_mcts.py \
    --model_name Vicuna \
    --verbose False \
    --data data/blocksworld/step_4.json \
    --max_depth 4 \
    --name rafa_roll60_13b_all \
    --rollouts 60 \
    --model_path lmsys/vicuna-13b-v1.3 \
    --num_gpus 1
```

Thank you very much!

Best,
Peng

**Comment by shuqike** [comment]
Hi Peng. How did you count the success rate? Could you share your experiment logs? Thanks.

**Comment by artpli** [comment]
Hi Shuqi @shuqike , I counted the success rates by `list total_correct (like line 197 in run_mcts.py)/#tasks (like 57 for 4-steps tasks)`.

**Comment by shuqike** [comment]
Our definition of success rate might be different from yours:
```
import os
import json
import argparse


def true_clip(x):
    return 1 if x else 0


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--run_name', type=str, default='mcts-run_1_Aug2_search_depth_3_alpha_01_rollouts_10')
    parser.add_argument('--num_trial', type=int, default=0)
    args = parser.parse_args()
    # if args.use_sample:
    data_path = os.path.join('logs', args.run_name, 'sample')
    sample_files = os.listdir(data_path)
    total_success = 0
    for file_name in sample_files:
        with open(os.path.join(data_path, file_name), 'r') as f:
            line = f.readline()
            try:
                num_success, num_sample = line.split(',')
            except:
                num_success = line.strip()
            if args.num_trial:
                total_success += eval(num_success)
            else:
                total_success += true_clip(eval(num_success))
    if args.num_trial:
        print(total_success/len(sample_files)/args.num_trial)
    else:
        print(total_success/len(sample_files))

    # sample accounting
    if not args.num_trial:
        data_path = os.path.join('logs', args.run_name, 'sample')
        sample_files = os.listdir(data_path)
        total_sample = 0
        total_success = 0
        for file_name in sample_files:
            with open(os.path.join(data_path, file_name), 'r') as f:
                line = f.readline()
                num_success, num_sample = line.split(',')
                try:
                    total_success += int(num_success)
                except ValueError:
                    total_success += bool(num_success)
                total_sample += int(num_sample)
        print(total_success, total_sample)
```

**Comment by shuqike** [comment]
@artpli Hi Peng, do you have other questions? If not, shall we close this issue?

**Comment by artpli** [comment]
@shuqike Hi, thank you for your reply! But I still can't align the logic of the code with the experimental result figures of the BlocksWorld tasks. Could you please guide me on how to use this code to obtain the success rate that changes with the number of steps, as shown in the Figure 7 (i.e., the red line in the figure)?

**Comment by artpli** [comment]
@shuqike Like, how to modify the parameter "num_trial" to obtain the red curve shown in the figure?

**Comment by shuqike** [comment]
@artpli For example, when we consider mcts, the `num_trial` argument is the number of rollouts, i.e. the `rollouts` argument we pass to run_mcts.py

**Comment by artpli** [comment]
@shuqike Oh, sorry for my previous misunderstanding. It turns out you ran all the eval datasets separately for different rollouts. Thanks for your consistently nice responses!
