### ISSUE TITLE
ENV Package issue

### ISSUE THREAD

**Issue by aqjichen** [agentification/RAFA_code#3]
Hi, I am interested in your masterpieces, and trying to reproduce the result, however, I am a little confused with Environment and DATA_PATH as attached, it seems like those variables are missing in the env package, how can I fix that issue, looking forward to your reply!
![env_issue](https://github.com/agentification/RAFA_code/assets/82919146/c6e5fae1-c812-4c3e-b457-e7871973f7e3)

**Comment by shuqike** [comment]
Have you checked our source code?
https://github.com/agentification/RAFA_code/blob/main/Game24/env/__init__.py
Those variables are well defined in this file.
